#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/mtXcontrol.jar:$APPDIR/lib/core.jar:$APPDIR/lib/themidibus.jar:$APPDIR/lib/launchpad.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/RXTXcomm.jar" mtXcontrol
